// src/views/About.vue
<script setup lang="ts">
// About.vue
import { onMounted } from 'vue'
import gsap from 'gsap'

onMounted(() => {
  // Bypassing strict GSAP opacity lockouts to ensure iOS Safari compliance
})
</script>

<template>
  <div class="about-view header-padding">
    <div class="container">
      <div class="about-header" style="text-align: center; margin-bottom: 5rem; padding-top: 5vh;">
        <h1 class="hero-title" style="font-size: clamp(2.5rem, 6vw, 4.5rem); letter-spacing: 0.1em;">
          A WORD FROM OUR <span style="color: var(--color-gold);">CREATOR</span>
        </h1>
        <div class="hz-divider" style="margin: 2rem auto;"></div>
      </div>

      <div class="about-content" style="max-width: 800px; margin: 0 auto; color: rgba(255, 255, 255, 0.7); font-size: 1.15rem; line-height: 1.9; font-family: var(--font-body);">
        
        <div class="about-content-block" style="margin-bottom: 4rem;">
          <h2 style="font-family: var(--font-heading); color: var(--color-gold-muted); letter-spacing: 0.2em; font-size: 1rem; margin-bottom: 1.5rem; text-transform: uppercase;">La Quête de Soi (The Quest for Self)</h2>
          <p style="margin-bottom: 1.5rem;">
            For many years, I searched for something without ever really knowing what or why. I always carried an overwhelming feeling of emptiness in my soul—a great void that never seemed to fill. Yet, I had a happy childhood. There was nothing in my past I could point to and say, "Ah, that's why I feel this way." My parents loved me, I had a beautiful family, and I was always encouraged to give my best. Despite it all, the feeling of not being "enough" persisted.
          </p>
          <p style="margin-bottom: 1.5rem;">
            Around the age of 13, I discovered drugs and alcohol, and I fell in love instantly. I loved how the void disappeared; that awkwardness I felt around others simply evaporated. It became my solution, and it worked—despite the chaos it created, even when I nearly lost my life in a car crash at 18. The lure of that soothing feeling was stronger than facing the emptiness. And it worked for 30 years. 
          </p>
          <p style="margin-bottom: 1.5rem;">
            Until it didn't. Until the relief turned into disgust, shame, and despair. I was completely broken. That was until a profound experience where I was transformed into a single molecule, alone in the vast universe of void and darkness. I was shown I had reasons to live. I realized the only way out was up, and the only way to climb was to finally admit I needed help.
          </p>
          <p>
            November 21, 2024, was the last time I consumed drugs or alcohol. Entering rehabilitation taught me that addiction is an affliction of the emotions. Through my journey, and through expressing these visceral emotions as a <strong>poet, songwriter, and tarot reader</strong>, I learned to process them rather than numb them. Be honest with yourself, follow your heart, be true. Because what I was truly searching for was myself. The void can only be filled from the inside.
          </p>
        </div>

        <div class="about-content-block" style="margin-bottom: 4rem;">
           <h2 style="font-family: var(--font-heading); color: var(--color-gold-muted); letter-spacing: 0.2em; font-size: 1rem; margin-bottom: 1.5rem; text-transform: uppercase;">The Architecture of the Self</h2>
           <p style="margin-bottom: 1.5rem;">
             Through meditation and faith, I had a realization: I couldn't fill the void with anything from the outside. So, I turned inward. I spent years immersing myself in sacred geometry, alchemical design, and the mathematics of resonance. I studied how 432Hz acts as the heartbeat of the Earth, reducing chaos, and how the Solfeggio scale strictly aligns our inner biological states. I realized that if I wanted to bridge the gap between ancient esoteric wisdom and my modern physical reality, I had to build the bridge myself.
           </p>
           <p>
             I began to see fashion as the architecture of the self. I started looking closely at the details—the geometry of fit, the exact harmonic resonance of 450GSM heavyweight cotton. I didn't want to just make clothes; I wanted to create a modern uniform. Something that feels like luxury loungewear, but behaves like a sacred shroud to cleanse the soul and keep negative energy at bay.
           </p>

        <div class="freq-hz-grid" style="margin-top: 3rem;">
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">174 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE FOUNDATION</strong><br/>
              Symbolizes grounding and security. This frequency represents the bedrock of emotional stability and foundational strength.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">285 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>QUANTUM HEALING</strong><br/>
              Symbolizes the restructuring of energetic boundaries. The 285 Hz aura represents rejuvenation and profound recovery.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">396 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE CATALYST</strong><br/>
              Symbolizes the liberation from guilt and the shedding of subconscious fears, representing the transformation of grief into bold joy.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">417 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE CLEARING</strong><br/>
              Symbolizes the clearing of past trauma and the courage to embrace positive shifts. It stands for undoing situations and forging ahead.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">528 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE LOVE FREQUENCY</strong><br/>
              Symbolizes transformation and miracles. Representing a deep emotional evolution, structural clarity, and the core of the biological lifecycle.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">639 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE HARMONIZER</strong><br/>
              Symbolizes harmony in connections, reflecting enhanced understanding, tolerance, and relational balance.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">741 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE AWAKENING</strong><br/>
              Symbolizes clear expression and the purification of creative spaces. It represents solutions, sharp intellect, and awakening intuition.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">852 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE INTUITION</strong><br/>
              Symbolizes inner strength and the piercing vision required to uncover your divine purpose while breaking free from illusions.
            </p>
          </div>
          <div class="hz-card glass">
            <div class="hz-header">
              <span class="hz-value">963 HZ</span>
              <span class="hz-status">SYMBOL: ALIGNED</span>
            </div>
            <div class="hz-divider"></div>
            <p class="hz-def">
              <strong>THE FREQUENCY OF GODS</strong><br/>
              Symbolizes divine consciousness and the limitless connection to the artistic source. Representing a return to Unity and structural perfection.
            </p>
          </div>
        </div>
        </div>

        <div class="about-content-block" style="margin-bottom: 4rem;">
          <h2 style="font-family: var(--font-heading); color: var(--color-gold-muted); letter-spacing: 0.2em; font-size: 1rem; margin-bottom: 1.5rem; text-transform: uppercase;">The Philosophy</h2>
          <p style="margin-bottom: 1.5rem;">
            My philosophy today is simple: <strong>Matter must serve Spirit, and healing must come from within.</strong> 
          </p>
          <p style="margin-bottom: 1.5rem;">
            When we hold onto anger or resentment, we poison our own souls and trap our minds in endless loops. To break free, we must look inward. As the ancient Alchemical motto dictates: <em>V.I.T.R.I.O.L. — Visita Interiora Terrae Rectificando Invenies Occultum Lapidem</em> (Visit the interior of the earth, and by rectifying, you will find the hidden stone). That stone is your true self.
          </p>
          <p style="margin-bottom: 1.5rem;">
            <strong>State of Resonance</strong> was born from this rebirth. Every piece, every garment, and every ritual tool we create is historically and materially calibrated to a specific frequency—whether it's the 432 Hz 'Heartbeat of the Earth' or the 963 Hz 'Frequency of the Gods'. They are not meant to magically fix your void; they are meant to reflect the resonance and honesty you are building from the inside out. 
          </p>
          <p style="margin-bottom: 2.5rem;">
            Life is still life, with its ups and downs, but it is infinitely sweeter when you can live 'just for today', in the present moment. State of Resonance is a synchronization point for seekers who are ready to elevate their own biological and spiritual frequencies, facing their reflections with absolute honesty.
          </p>
          <div style="display: flex; align-items: center; gap: 1rem;">
            <div style="font-family: 'Cormorant Garamond', serif; font-size: 2rem; color: var(--color-gold); font-style: italic;">— Jay</div>
          </div>
        </div>

      </div>
    </div>

    <!-- Shop CTA — every page should have a conversion path -->
    <section style="border-top: 1px solid rgba(212,175,55,0.08); margin-top: 8vh; padding: 10vh 0; text-align: center; background: #000;">
      <div class="container">
        <p style="font-size: 0.6rem; letter-spacing: 0.4em; text-transform: uppercase; color: var(--color-gold-muted); margin-bottom: 1.5rem; opacity: 0.6;">✦ THE COLLECTION ✦</p>
        <h2 style="font-family: var(--font-heading); font-size: clamp(2rem, 5vw, 3.5rem); font-weight: 700; color: #fff; margin-bottom: 1rem; letter-spacing: 0.02em;">Wear Your Frequency</h2>
        <p style="font-size: 0.95rem; color: rgba(255,255,255,0.45); max-width: 480px; margin: 0 auto 3rem; line-height: 1.7;">Each garment is designed to reflect the resonance you are building from the inside out. Limited runs. Ships from Canada.</p>
        <div style="display: flex; gap: 1.5rem; justify-content: center; flex-wrap: wrap;">
          <router-link to="/best-sellers" class="btn-premium" style="padding: 1rem 2.5rem; letter-spacing: 0.2em; font-size: 0.8rem;">SHOP THE COLLECTION</router-link>
          <router-link to="/quiz" class="btn-outline" style="padding: 1rem 2rem; letter-spacing: 0.15em; font-size: 0.8rem;">Find Your Frequency →</router-link>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.about-view {
  min-height: 100dvh;
  background-color: var(--color-bg);
  padding-bottom: 10vh;
}
.hz-divider {
  height: 1px;
  background: linear-gradient(90deg, transparent, var(--color-gold-muted), transparent);
  width: 150px;
  margin: 1rem 0;
}
.about-content p {
  color: rgba(255, 255, 255, 0.8);
}
.about-content strong {
  color: white;
  letter-spacing: 0.05em;
}

/* Solfeggio Grid Styles */
.freq-hz-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
}
.hz-card {
  padding: 2.5rem;
  text-align: left;
  border: 1px solid rgba(212, 175, 55, 0.1);
  transition: all 0.5s var(--ease-out-expo);
}
.hz-card:hover {
  border-color: var(--color-gold);
  background: rgba(212, 175, 55, 0.05);
  transform: translateY(-5px);
}
.hz-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}
.hz-value {
  font-family: var(--font-heading);
  font-size: 2rem;
  color: var(--color-gold);
}
.hz-status {
  font-size: 0.6rem;
  letter-spacing: 0.2em;
  color: #4ade80;
}
.hz-def {
  font-size: 0.9rem;
  line-height: 1.6;
  color: rgba(255,255,255,0.7);
}
@media (max-width: 968px) {
  .freq-hz-grid {
    grid-template-columns: 1fr;
    gap: 2rem;
  }
}
</style>

// src/app/about/page.tsx
import Image from 'next/image';

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-black">
      {/* ═══════ HERO ═══════ */}
      <section className="relative w-full pt-48 pb-32 flex flex-col items-center justify-center border-b border-[rgba(255,255,255,0.05)] overflow-hidden">
        <div className="absolute inset-0 bg-[url('/luxury-occult-bg.png')] bg-cover bg-center opacity-30 mix-blend-luminosity" />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black" />
        
        <div className="relative z-10 text-center px-6 max-w-4xl max-auto">
          <p className="text-[var(--color-gold)] uppercase tracking-[0.4em] text-xs mb-6 inline-block border-b border-[var(--color-gold-muted)] pb-2 pr-1">The Origin</p>
          <h1 className="text-5xl md:text-6xl font-serif text-white mb-8 tracking-wide uppercase leading-tight">
            More Than Fabric.<br />A Declaration.
          </h1>
          <p className="text-gray-400 font-sans text-sm md:text-base tracking-widest uppercase max-w-2xl mx-auto leading-relaxed">
            State of Resonance was born from a simple belief: what you wear should mean something.
          </p>
        </div>
      </section>

      {/* ═══════ EDITORIAL GRID ═══════ */}
      <section className="py-24 px-6 max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-16 md:gap-24 items-center mb-32">
          <div className="order-2 md:order-1 relative aspect-[4/5] border border-[rgba(255,255,255,0.05)] p-4">
            <div className="relative w-full h-full bg-[rgba(255,255,255,0.02)]">
              <Image src="/fabric-texture.png" alt="Heavyweight cotton texture" fill className="object-cover opacity-60 mix-blend-luminosity grayscale" />
              <div className="absolute inset-0 bg-gradient-to-tr from-black via-transparent to-transparent opacity-80" />
            </div>
            <div className="absolute -bottom-6 -right-6 md:-left-6 w-32 h-32 border-b border-l md:border-r-0 border-[var(--color-gold-muted)] opacity-30 pointer-events-none" />
          </div>
          
          <div className="order-1 md:order-2 space-y-8">
            <div className="flex items-center gap-4 mb-4">
              <span className="text-[var(--color-gold-muted)] font-serif text-2xl">01</span>
              <div className="h-[1px] flex-grow bg-gradient-to-r from-[var(--color-gold-muted)] to-transparent opacity-30" />
            </div>
            <h2 className="font-serif text-3xl text-white uppercase tracking-widest">The Philosophy</h2>
            <div className="space-y-6 text-gray-300 font-sans text-sm leading-relaxed tracking-wide">
              <p>Every piece in our collection is designed around sacred geometry, ancient symbols, and intentional frequencies. We don&apos;t just make clothes — we create artifacts that carry deep, personalized meaning.</p>
              <p>Based in Canada, we serve a global community of seekers, creators, and individuals who understand that style is An extension of spirit. Quality over quantity. Depth over trend.</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-16 md:gap-24 items-center">
          <div className="space-y-8">
            <div className="flex items-center gap-4 mb-4">
              <span className="text-[var(--color-gold-muted)] font-serif text-2xl">02</span>
              <div className="h-[1px] flex-grow bg-gradient-to-r from-[var(--color-gold-muted)] to-transparent opacity-30" />
            </div>
            <h2 className="font-serif text-3xl text-white uppercase tracking-widest">The Process</h2>
            <div className="space-y-6 text-gray-300 font-sans text-sm leading-relaxed tracking-wide">
              <p>This is a hyper-personal project. Each piece is fundamentally made to order. The garments are embroidered right here at my local embroidery shop, and the graphics are printed individually as orders arrive.</p>
              <p>That means every single artifact passes directly through my hands. I personally check the stitching, the print weight, and the feel to ensure the absolute best quality before it reaches you.</p>
              <div className="p-6 border border-[rgba(212,175,55,0.2)] bg-[rgba(212,175,55,0.02)] mt-8">
                <p className="text-[var(--color-gold-muted)] font-sans text-xs uppercase tracking-widest leading-relaxed">
                  Because of this intensely hands-on process, <strong className="text-white">only 10 pieces of each design are ever made.</strong> Once those 10 units are claimed, I move on to entirely new prints.
                </p>
              </div>
            </div>
          </div>
          
          <div className="relative aspect-square md:aspect-[4/5] border border-[rgba(255,255,255,0.05)] overflow-hidden group">
            <Image src="/jayson-social.jpg" alt="Hands-on process" fill className="object-cover opacity-80 mix-blend-luminosity transform group-hover:scale-105 transition-transform duration-1000" />
            <div className="absolute inset-0 bg-black/40 group-hover:bg-black/20 transition-colors duration-1000" />
          </div>
        </div>
      </section>

      {/* ═══════ FOUNDER STORY ═══════ */}
      <section className="py-32 px-6 max-w-4xl mx-auto border-t border-[rgba(255,255,255,0.05)]">
        <div className="flex flex-col items-center text-center">
          <p className="text-[var(--color-gold)] uppercase tracking-[0.4em] text-xs mb-6 inline-block border-b border-[var(--color-gold-muted)] pb-2 pr-1">The Architect</p>
          <h2 className="font-serif text-3xl md:text-4xl text-white uppercase tracking-widest mb-12">A Word from the Founder</h2>
          
          <div className="space-y-6 text-gray-300 font-sans text-sm md:text-base leading-relaxed tracking-wide text-left md:text-justify max-w-3xl">
            <p className="text-[var(--color-gold)] font-serif text-xl md:text-2xl mb-8 text-center uppercase tracking-widest">The Quest for Self.</p>
            <p>For many years, I searched for something without ever really knowing what or why. I carried an overwhelming emptiness in my soul—a void that never seemed to fill. Despite a beautiful family and a happy childhood, the feeling of not being &quot;enough&quot; persisted.</p>
            <p>At 13, I found a way to make that awkwardness evaporate. It became my solution, and it worked for 30 years—despite the chaos it created. Until the relief turned into despair. I was completely broken.</p>
            <p>November 21, 2024, was the day everything changed. Entering rehabilitation taught me that the only way to climb out of the dark was to finally admit I needed help. I learned to process my emotions rather than numb them. Because what I was truly searching for was myself. The void can only be filled from the inside.</p>
            <p>Through meditation, faith, and immersing myself in the mathematics of resonance and alchemical design, I realized I had to build the bridge between ancient esoteric wisdom and my modern reality.</p>
            <p>I began to see fashion as the architecture of the self. I wanted to create a modern uniform—something that feels like luxury loungewear, but behaves like a sacred shroud to cleanse the soul. <strong>State of Resonance was born from this rebirth.</strong></p>
            <p>Every artifact and garment is calibrated to a specific frequency—whether it&apos;s the 432Hz &apos;Heartbeat of the Earth&apos; or the 963Hz &apos;Frequency of the Gods&apos;. They are not meant to magically fix your void; they are meant to reflect the resonance and honesty you are building from the inside out. As the ancient Alchemical motto dictates: <em>V.I.T.R.I.O.L. — Visit the interior of the earth, and by rectifying, you will find the hidden stone.</em> That stone is your true self.</p>
            <p className="text-center font-serif text-[var(--color-gold-muted)] italic mt-8 text-lg">Life is infinitely sweeter when you can live &apos;just for today&apos;.</p>
            <p className="text-center text-white tracking-widest uppercase text-xs mt-4">Welcome to the synchronization point.</p>
          </div>
          
          <div className="mt-16 flex flex-col items-center">
            <div className="w-16 h-[1px] bg-gradient-to-r from-transparent via-[var(--color-gold-muted)] to-transparent mb-6" />
            <p className="font-serif italic text-white text-xl">Jay</p>
            <p className="text-xs text-[var(--color-gold-muted)] uppercase tracking-widest mt-2">Founder & Creator</p>
          </div>
        </div>
      </section>

      {/* ═══════ QUOTE ═══════ */}
      <section className="py-32 px-6 border-t border-[rgba(255,255,255,0.05)] bg-[radial-gradient(ellipse_at_center,_rgba(212,175,55,0.03)_0%,_black_70%)] text-center">
        <p className="text-[var(--color-gold-muted)] font-serif italic text-2xl md:text-4xl max-w-3xl mx-auto leading-relaxed shadow-gold">
          &quot;Wear the frequency.<br />Become the resonance.&quot;
        </p>
      </section>
    </div>
  );
}
